### ISSUE TITLE
Error in called.segobj.list[[i]] : subscript out of bounds

### ISSUE THREAD

**Issue by chenhd9** [ShixiangWang/DoAbsolute#13]
I run it with maf and seg file. It worked well before "Absolute summarize".
![image](https://user-images.githubusercontent.com/49526737/88245602-5f25e300-ccca-11ea-8cd8-9a398296fe9e.png)
Could you give me some help?

**Comment by ShixiangWang** [comment]
The error comes from the following code

https://github.com/ShixiangWang/DoAbsolute/blob/2b49298e967279388fcef3d4fa81db9282a25886/R/DoAbsolute.R#L417-L429

Could you check you temp directory

![image](https://user-images.githubusercontent.com/25057508/88247147-49ff8300-cccf-11ea-9c86-536837223bd8.png)

And see if you can find the two files?

![image](https://user-images.githubusercontent.com/25057508/88247166-5d125300-cccf-11ea-989a-12313dd0bf86.png)

**Comment by chenhd9** [comment]
![image](https://user-images.githubusercontent.com/49526737/88247658-23dae280-ccd1-11ea-99e4-9e40bc7d490f.png)
yes.

**Comment by ShixiangWang** [comment]
That's strange, the problem should come from ABSOLUTE package code, please zip the two files and send to me by email w_shixiang@163.com, and I will test it.

**Comment by ShixiangWang** [comment]
@chenhd9 Yes, you are right. I can reproduce your error, and this is caused by your low purity sample.

For ABSOLUTE, it will only `review` the samples with `call status` is `called`. 

![image](https://user-images.githubusercontent.com/25057508/88249067-d3b24f00-ccd5-11ea-90cf-996b756f6f85.png)

![image](https://user-images.githubusercontent.com/25057508/88249085-e2990180-ccd5-11ea-88e6-214562ce69e5.png)

Therefore, the program cannot find any results with called status, and got a zero element list.

You should input more samples when use **DoAbsolute**.

**Comment by chenhd9** [comment]
wow~Thank you for your patience. I merge all the sample and it worked!
